const {
  SUPERUSER_NAME,
  SUPERUSER_EMAIL,
  SUPERUSER_PASSWORD,
  APP_TITLE,
  RECORDER_FOLDER,
  RECORDER_CHUNK_DURATION,
} = process.env;

export const APP = {
  TITLE: APP_TITLE,
};

export const SUPERUSER = {
  NAME: SUPERUSER_NAME,
  EMAIL: SUPERUSER_EMAIL,
  PASSWORD: SUPERUSER_PASSWORD,
};

export const RECORDER = {
  FOLDER: RECORDER_FOLDER,
  CHUNK_DURATION: RECORDER_CHUNK_DURATION,
};

export default { SUPERUSER, APP, RECORDER };
