- name: Install packages that docker-compose depends on
  apt:
    name:
      - python3-pip
      - libffi-dev
      - libssl-dev
    update_cache: yes
  become: true
  tags:
    - docker-compose

- name: Install docker-compose by pip as root
  pip:
    name: docker-compose
  become: true
  tags:
    - docker-compose
