name: Build

# Trigger the workflow on pull request activity
on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]

defaults:
  run:
    shell: bash
    working-directory: app

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: 1.10.2
      - run: meteor npm install
      - run: npm run build
